# 1. Create a 3x3x3 array with random values 

In [6]:
import numpy as np
np.random.random((3,3,3))

array([[[0.77872984, 0.42020123, 0.8094332 ],
        [0.58167427, 0.93453965, 0.3613666 ],
        [0.80395148, 0.27144487, 0.65099176]],

       [[0.46105282, 0.29555955, 0.18070625],
        [0.03969348, 0.09525338, 0.40766667],
        [0.67132853, 0.360115  , 0.79494251]],

       [[0.49887843, 0.91236555, 0.10115053],
        [0.70010669, 0.02025709, 0.26452793],
        [0.93569792, 0.2964347 , 0.10814482]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [17]:
np.diag(1+np.arange(4),-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [24]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [29]:
ar = np.random.random((5,5))
armax, armin = ar.max(), ar.min()
ar = (ar - armin)/(armax - armin)
print(ar)

[[0.44917735 0.02982181 0.66867097 0.15717431 0.3431423 ]
 [0.83359443 0.12484079 0.1211568  0.58159217 0.57233092]
 [0.55435279 0.96139252 0.30870947 0.72512944 0.52414285]
 [0.04596026 0.26851655 0.69783259 0.63124281 0.22321749]
 [0.         0.67022847 0.0219839  0.41908963 1.        ]]


# 5.  How to find common values between two arrays?

In [31]:
ar1 = np.random.randint(0,15,15)
ar2 = np.random.randint(0,15,15)
print(np.intersect1d(ar1,ar2))

[ 0  1  2  5 11 13]


# 6.How to get the dates of yesterday, today and tomorrow?

In [38]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today')+np.timedelta64(1)
print(yesterday,today,tomorrow)

2020-07-27 2020-07-28 2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [41]:
ar1 = np.random.randint(0,15,15)
ar2 = np.random.randint(0,15,15)
equal = np.allclose(ar1,ar2)
equal

False

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [51]:
ve = np.random.random((10))
ve[ve.argmax()] = 0
ve

array([0.        , 0.03332219, 0.16396869, 0.47856286, 0.31827641,
       0.21484594, 0.31367847, 0.43161492, 0.14627215, 0.16800197])

# 9. How to print all the values of an array?

In [53]:
np.random.random((5,5))

array([[0.17383846, 0.86865653, 0.11022493, 0.25689736, 0.91618958],
       [0.57117684, 0.12395713, 0.71831396, 0.56026   , 0.55508057],
       [0.18530043, 0.71683159, 0.98185207, 0.99203488, 0.69439167],
       [0.32254937, 0.97386739, 0.91105301, 0.53668297, 0.6215866 ],
       [0.86242253, 0.34440051, 0.98131901, 0.26590774, 0.23496344]])

# 10.Subtract the mean of each row of a matrix

In [67]:
ar = np.random.random((5,5))
y = ar-ar.mean()
print(y)

[[ 0.28484072  0.23426262 -0.30058745  0.3990587  -0.20074706]
 [ 0.04636588  0.24133496  0.12435783 -0.43028428  0.42791103]
 [-0.13925744 -0.46090488 -0.29312694 -0.457864    0.08093625]
 [-0.19910223  0.23386043  0.41058818 -0.14476159 -0.40396423]
 [-0.19392591  0.49754712  0.17198159  0.46861172 -0.39713102]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [70]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
print(Z)
print(I)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2 4 4 8 6 6 7 3 6 8 0 4 2 1 8 9 6 8 7 5]


In [71]:
np.add.at(Z, I, 1)
print(Z)

[2. 2. 3. 2. 4. 2. 5. 3. 5. 2.]


# 12.How to get the diagonal of a dot product?

In [75]:
A = np.random.random((5,5))
B = np.random.random((5,5))
np.diag(np.dot(A, B))

array([1.4286855 , 1.66737901, 1.85618172, 0.78294673, 0.98079605])

# 13.How to find the most frequent value in an array?

In [78]:
z = np.random.randint(0,50,15)
print(np.bincount(z).argmax())

31


# 14.How to get the n largest values of an array

In [80]:
Z = np.arange(10000)
n = 10
print (Z[np.argsort(Z)[-n:]])

[9990 9991 9992 9993 9994 9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [82]:
Z = np.array([("Hello", 2.5, 3),("World", 3.6, 2)])
print(Z)
R = np.core.records.fromarrays(Z.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print(R)

[['Hello' '2.5' '3']
 ['World' '3.6' '2']]
[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
